FROM node:20-buster-slim

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY frontend/package.json frontend/
COPY frontend/ ./frontend

# Install pnpm and build
RUN npm install -g pnpm@10.23.0
RUN pnpm install --silent
RUN cd frontend && pnpm build

# Serve built files using serve
RUN npm install -g serve@14
CMD ["sh", "-c", "servedir=frontend/dist && serve -s $servedir -l 5173"]

EXPOSE 5173
